version: '3'
services:

  rest:
    image: datastrata/rest-ts-node
    container_name: rest
    #restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - opsnet
    stdin_open: true
    tty: true

  records:
    image: datastrata/ds-record-submission
    container_name: ds-record-submission
    #restart: unless-stopped
    ports:
      - 3002:3002
    networks:
      - opsnet
    stdin_open: true
    tty: true

  socket:
    image: datastrata/ds-socket
    container_name: ds-socket
    #restart: unless-stopped
    ports:
      - 3030:3030
    networks:
      - opsnet
    stdin_open: true
    tty: true

#  payments:
#    image: datastrata/stripe-payments
#    container_name: payments
#    #restart: unless-stopped
#    ports:
#      - 3001:3001
#    networks:
#      - opsnet
#    stdin_open: true
#    tty: true

  web:
    image: datastrata/web-mobile
    container_name: web
#    restart: unless-stopped
    depends_on:
      - rest
      - records
#      - payments
    ports:
      - 80:80
      - 443:443
    networks:
      - opsnet
    stdin_open: true
    tty: true

networks:
  opsnet:

